"""FLEURS BCP-47 config code -> candidate ISO-639-3 code(s) for PHOIBLE join.

Each value is an ordered list of candidate ISO-639-3 codes; the analysis resolves
to the first one that actually exists in PHOIBLE. Macrolanguages list the
individual code first (PHOIBLE usually catalogs the doculect under it) then the
macro code as fallback.
"""

FLEURS_TO_ISO = {
    "af_za": ["afr"],
    "am_et": ["amh"],
    "ar_eg": ["arz", "arb"],          # Egyptian Arabic; fall back to Standard
    "as_in": ["asm"],
    "ast_es": ["ast"],
    "az_az": ["azj", "aze"],
    "be_by": ["bel"],
    "bg_bg": ["bul"],
    "bn_in": ["ben"],
    "bs_ba": ["bos", "hbs"],
    "ca_es": ["cat"],
    "ceb_ph": ["ceb"],
    "ckb_iq": ["ckb"],
    "cmn_hans_cn": ["cmn"],
    "cs_cz": ["ces"],
    "cy_gb": ["cym"],
    "da_dk": ["dan"],
    "de_de": ["deu"],
    "el_gr": ["ell"],
    "en_us": ["eng"],
    "es_419": ["spa"],
    "et_ee": ["ekk", "est"],
    "fa_ir": ["pes", "fas"],
    "ff_sn": ["fuc", "fuf", "ful"],
    "fi_fi": ["fin"],
    "fil_ph": ["fil", "tgl"],
    "fr_fr": ["fra"],
    "ga_ie": ["gle"],
    "gl_es": ["glg"],
    "gu_in": ["guj"],
    "ha_ng": ["hau"],
    "he_il": ["heb"],
    "hi_in": ["hin"],
    "hr_hr": ["hrv", "hbs"],
    "hu_hu": ["hun"],
    "hy_am": ["hye"],
    "id_id": ["ind"],
    "ig_ng": ["ibo"],
    "is_is": ["isl"],
    "it_it": ["ita"],
    "ja_jp": ["jpn"],
    "jv_id": ["jav"],
    "ka_ge": ["kat"],
    "kam_ke": ["kam"],
    "kea_cv": ["kea"],
    "kk_kz": ["kaz"],
    "km_kh": ["khm"],
    "kn_in": ["kan"],
    "ko_kr": ["kor"],
    "ky_kg": ["kir"],
    "lb_lu": ["ltz"],
    "lg_ug": ["lug"],
    "ln_cd": ["lin"],
    "lo_la": ["lao"],
    "lt_lt": ["lit"],
    "luo_ke": ["luo"],
    "lv_lv": ["lvs", "lav"],
    "mi_nz": ["mri"],
    "mk_mk": ["mkd"],
    "ml_in": ["mal"],
    "mn_mn": ["khk", "mon"],
    "mr_in": ["mar"],
    "ms_my": ["zsm", "msa"],
    "mt_mt": ["mlt"],
    "my_mm": ["mya"],
    "nb_no": ["nob", "nor"],
    "ne_np": ["npi", "nep"],
    "nl_nl": ["nld"],
    "nso_za": ["nso"],
    "ny_mw": ["nya"],
    "oc_fr": ["oci"],
    "om_et": ["gax", "orm"],
    "or_in": ["ory", "ori"],
    "pa_in": ["pan"],
    "pl_pl": ["pol"],
    "ps_af": ["pbt", "pus"],
    "pt_br": ["por"],
    "ro_ro": ["ron"],
    "ru_ru": ["rus"],
    "sd_in": ["snd"],
    "sk_sk": ["slk"],
    "sl_si": ["slv"],
    "sn_zw": ["sna"],
    "so_so": ["som"],
    "sr_rs": ["srp", "hbs"],
    "sv_se": ["swe"],
    "sw_ke": ["swh", "swa"],
    "ta_in": ["tam"],
    "te_in": ["tel"],
    "tg_tj": ["tgk"],
    "th_th": ["tha"],
    "tr_tr": ["tur"],
    "uk_ua": ["ukr"],
    "umb_ao": ["umb"],
    "ur_pk": ["urd"],
    "uz_uz": ["uzn", "uzb"],
    "vi_vn": ["vie"],
    "wo_sn": ["wol"],
    "xh_za": ["xho"],
    "yo_ng": ["yor"],
    "yue_hant_hk": ["yue"],
    "zu_za": ["zul"],
}
