#!/usr/bin/env python3
"""
Scan every language's shipped audio for SILENT files.

⚠ THE SECOND FLEURS AUDIO DEFECT, AND IT IS NOT THE WELSH ONE. Run 36 found 585 Welsh utterances
whose audio is TRUNCATED to ~1.4 s of a ~14 s sentence. This is a different failure with the same
consequence: `es_419` ships 490 files (17.5% of the split) that are FULL LENGTH and DIGITALLY SILENT
— rms ~8e-6, peak 0.0000, against 0.02-0.10 for normal rows. A duration check cannot see it; the
files are the right length and contain nothing.

Both are catastrophic TRAINING PAIRS — a full sentence of IPA against silence teaches the model that
the text maps to no audio at all — and neither is visible to any text-side gate, because the
transcript and the IPA are both fine. Only the PAIR is broken.

⚠ WHY THIS SCRIPT EXISTS WHEN THE RECOGNIZER ALREADY FOUND THEM. On es_419 the correspondence was
EXACT: 490 silent files, 490 empty recognizer outputs, zero either way. So an empty ASR result is a
perfect proxy *there*. But that is a measured fact about one language, not a guarantee — a silent
file could in principle draw a hallucinated phone or two, and a noisy-but-speechless file would draw
several. Measuring the audio directly is the check that does not depend on the recognizer behaving.

  python3 scan_silent_audio.py                  # all languages
  python3 scan_silent_audio.py es_419 cy_gb     # named languages

Writes `work/silent_audio.tsv` (lang, wav, rms, seconds) for `exclude_defective.py` to consume.
"""
from __future__ import annotations

import argparse
import io
import os
import sys
import tarfile

import numpy as np
import soundfile as sf

ROOT = "/mnt/data/omnivoice_ipa"
AUDIO = f"{ROOT}/corpus/audio_cache/data"
OUT = f"{ROOT}/work/silent_audio.tsv"

# ⚠ Measured, not guessed: the silent es_419 files sit at rms ~8e-6 and normal speech at 0.02-0.10 —
# four orders of magnitude apart, so the threshold is nowhere near anything real.
SILENCE_RMS = 1e-4


def scan(lang: str) -> list[tuple[str, float, float]]:
    tar_path = f"{AUDIO}/{lang}/audio/train.tar.gz"
    if not os.path.exists(tar_path):
        return []
    out = []
    with tarfile.open(tar_path, "r:gz") as tf:
        for m in tf:
            if not m.isfile() or not m.name.endswith(".wav"):
                continue
            try:
                a, sr = sf.read(io.BytesIO(tf.extractfile(m).read()), dtype="float32")
            except Exception:
                continue
            if a.ndim > 1:
                a = a.mean(1)
            rms = float(np.sqrt((a ** 2).mean())) if a.size else 0.0
            if rms < SILENCE_RMS:
                out.append((m.name.split("/")[-1], rms, len(a) / sr))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("langs", nargs="*")
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args()

    langs = a.langs or sorted(d for d in os.listdir(AUDIO)
                              if os.path.exists(f"{AUDIO}/{d}/audio/train.tar.gz"))
    rows = []
    for lang in langs:
        hits = scan(lang)
        rows += [(lang, w, r, s) for w, r, s in hits]
        print(f"{lang:<12} {len(hits):>5} silent", flush=True)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("# lang\twav\trms\tseconds — generated by scan_silent_audio.py\n")
        for lang, w, r, s in rows:
            f.write(f"{lang}\t{w}\t{r:.8f}\t{s:.2f}\n")
    print(f"\n{len(rows)} silent files -> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
